### ISSUE TITLE
UI Mockup & Implementation

### ISSUE THREAD

**Issue by aerjay** [aerjay/algal-blooms#11]
@xie-james72 @nguc @benjaminlee1 @KalRadikov  Theoretically what do want to show the user?

**Comment by KalRadikov** [comment]
assuming the backend isn't done by friday, just 5-6 post-processed images for the summer months.
assuming it's done by friday, 
* a date range input field to query satellite images from point A to point B (can do one image every 2 weeks or something idk)
* a location input field
* a graph plotting the ratios per time
* images of each time interval plot on the graph

that is my thinking
